### ISSUE TITLE
stright to google web tv...

### ISSUE THREAD

**Issue by shimondoodkin** [doug/depthjs#1]

**Comment by ghost** [comment]
i agree!!!

**Comment by azinman** [comment]
The SDK is not yet out for Google TV.

You can see what's already available by Hitachi.

http://gigaom.com/video/show-of-hands-gestures-control-hitachi-tv/

**Comment by shimondoodkin** [comment]
Hitachi's tv control not that smooth and precise.

**Comment by ghost** [comment]
i am not interested in having an "integrated tv". Prefer to have my own HTPC (windows) with kinetc. 
This will allow watching as much streamed TV without getting involved in the horrible lock in ware about content currently raging. 
i prefer just to side step the whole issue.

I am looking for a nice htpc at the moment

**Comment by shimondoodkin** [comment]
gedw99 i like your idea more then google tv.

probably google tv should be a provider of a hd cable tv over the internet
and maybe a free linux os tv with tv watching software suit or windows watching

**Comment by ghost** [comment]
hey Shim....

The scenejs framework is what i will use as a front end. Pure html5 and webg.
Then i was workong on an automatic vpn switcher that runs on its own node.
It just listens for URLS and then flips over the connection to the current vpn server.
for for Hulu you want to switch to a US vpn server. Plonk it down in the basement where the fibre connection WAN is and your good to go.

As far as finding content, there will alwasy be portals with this type of stuff and screen scrapers around. 

The base system will all be Nodejs based.
