### ISSUE TITLE
How do I use it?....

### ISSUE THREAD

**Issue by FethrdWlf** [doug/depthjs#11]
So, I've installed all of the drivers for Kinect from OpenKinect (I needed those, right?), and I have the DepthJS extension installed. However, whenever I try to use the DepthJS software, it won't recognize that my Kinect is plugged in. The extension works fine, but the options to "Connect to Kinect" are grayed out. Help?

**Comment by azinman** [comment]
Are you running the two backends? They are in cv and backend.

This is not yet ready for end users. We are actively working on packaging this up.

**Comment by FethrdWlf** [comment]
What exactly are the backends?....

**Comment by azinman** [comment]
The directories cv (the freenect/opencv part) & backend (the 0mq -> websocket server).

Remember, all this goes away when we package it into a nice extension. We have two competing and parallel efforts given Firebreath is not quite mature.
