### ISSUE TITLE
import zmq error

### ISSUE THREAD

**Issue by handonam** [doug/depthjs#12]
Hey all.

I'm having some problems with trying to get zeromq to work with the python backend.  when i run python, i get:

<pre>
Traceback (most recent call last):
  File "Backend.py", line 1, in [module]
     import zmq
ImportError: No module named zmq
</pre>

I think i'm having some library linking problems or something.  Do you have any idea how I can get my zeromq libraries set up correctly?  i installed it according to http://www.zeromq.org/intro:get-the-software
and ran ldconfig.

**Comment by doug** [comment]
try installing the latest versions of zeromq from source off of github

**Comment by handonam** [comment]
doesn't seem to work :(

**Comment by handonam** [comment]
woops i accidentally closed it

**Comment by doug** [comment]
it would be a pyzmq issue, check the docs and code here https://github.com/zeromq/pyzmq and check in with them as they know more about installation issues of pyzmq
