### ISSUE TITLE
Windows Ready?

### ISSUE THREAD

**Issue by Schizo** [doug/depthjs#15]
Hi @ all, 

Before getting started it would be nice to know if the framework is already compatible with windows or not, before running into big issues.

thanks

**Comment by azinman** [comment]
Yah its not really anything ready at this point :) but surely not windows. We are only aiming for Mac/Linux support at this point.

--Aaron (on mobile)

**Comment by royshil** [comment]
@Schizo Windows is going to be implemented very soon (Chrome only at this point).
