### ISSUE TITLE
Unable to build DepthJS NPAPI plugin.

### ISSUE THREAD

**Issue by kench** [doug/depthjs#16]
I'm working on porting DepthJS to Linux and I've encountered an issue compiling DepthJS on both Mac OS X and Linux.

I attempted to fix it myself by removing the libfreenect.hpp file and I have the following output:

https://gist.github.com/1033151

**Comment by azinman** [comment]
I'm not sure that you should remove the libfreenect.hpp file. It worked not too long ago on Linux, although we have been concentrating on the Mac. For the moment, we're trying to improve the algorithms (implementing a Kalman filter) and not on platforms.

I'd also say make sure you've updated the drivers... and if the API has changed, we'd appreciate any patches :)

Best,
Aaron

## 

aaron zinman :: mit media lab :: web.media.mit.edu/~azinman (http://web.media.mit.edu/%7Eazinman) :: protocol.by/azinman (http://protocol.by/azinman) :: courteous.ly/mhuoL3 (http://courteous.ly/mhuoL3)

**Comment by kench** [comment]
After speaking with the folks on #openkinect, several functions were depreciated.
I patched DepthJS to work with the newest libfreenect and I created a Linux build script that now produces a shared object.
