### ISSUE TITLE
Install. Got stuck with PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by Laurentius** [doug/depthjs#18]
Hello,

I tried to install everything for chrome and tried build-mac.sh and all I get is the following error:

Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found

I tried to reconfigure PKG_CONFIG_PATH by doing this:

export PKG_CONFIG_PATH =  .....

But it doesn't work.

I'm no expert with this so I'm doing something wrong. Maybe you could give me a hint on how to solve this?

Thanks in advance

**Comment by azinman** [comment]
That shouldn't be... opencv comes as a natively built library that it should use.

I noticed things seem to be broken as it wouldn't build for me right now, so perhaps ask roys@media.mit.edu (mailto:roys@media.mit.edu) for help as my phd thesis is due in like 11 days.

Best,Aaron

## 

aaron zinman :: mit media lab :: web.media.mit.edu/~azinman (http://web.media.mit.edu/%7Eazinman) :: protocol.by/azinman (http://protocol.by/azinman) :: courteous.ly/mhuoL3 (http://courteous.ly/mhuoL3)

**Comment by bobbylox** [comment]
OK.  This was seven months ago now, but I'm having the same issue as this person.  Any idea what's up there?

**Comment by royshil** [comment]
@bobbylox OpenCV is no longer a part of the project. All dependencies on OpenCV should have been dropped.
