### ISSUE TITLE
installation docs

### ISSUE THREAD

**Issue by ghost** [doug/depthjs#2]
I want to get this going but need a little more info in the form of installation notes.

Also the notes on the coding for custom hand gestures woudl be useful.
I want to hook this up to a webgl 3d world and so the hand gestures woudl be very different.

**Comment by azinman** [comment]
How technical are you?

We are working on a 1-click install package that will simplify a lot. I'd wait a week or two unless you're willing to get your hands wet.

This guide (in portugese, google translate works well) shows how to set things up on Ubuntu currently.

http://info.abril.com.br/noticias/blogs/zonalivre/desenvolvimento/um-guia-para-hackear-o-kinect/

**Comment by ghost** [comment]
On linux i am very average. But at the very least a basic setup guide woudl still be good 
Am happy to wait 2 weeks :)
