### ISSUE TITLE
Unable to build Chrome Extension in Snow Leopard (10.6.7)

### ISSUE THREAD

**Issue by rubikzube** [doug/depthjs#22]
I used homebrew to install the dependencies and modified the build-mac shell script slightly to use the 10.6 developer SDK's... now I can almost build... here is the log:

Assuming homebrew install of libusb and libfreenect
depthjs.cc:162: warning: ‘bool setupDevice()’ defined but not used
ocv_freenect.cpp: In function ‘void\* ocvFreenectThread(void*)’:
ocv_freenect.cpp:377: warning: comparison between signed and unsigned integer expressions
ocv_freenect.cpp:383: warning: comparison between signed and unsigned integer expressions
ocv_freenect.cpp:447: warning: comparison between signed and unsigned integer expressions
bg_fg_blobs.cpp: In function ‘cv::Scalar refineSegments(const cv::Mat&, cv::Mat&, cv::Mat&, std::vectorcv::Point_<int, std::allocatorcv::Point_<int > >&, std::vectorcv::Point_<int, std::allocatorcv::Point_<int > >&, cv::Point2i&)’:
bg_fg_blobs.cpp:51: warning: comparison between signed and unsigned integer expressions
bg_fg_blobs.cpp:59: warning: comparison between signed and unsigned integer expressions
bg_fg_blobs.cpp:66: warning: comparison between signed and unsigned integer expressions

Undefined symbols for architecture i386:
  "_freenect_find_video_mode", referenced from:
      Freenect::FreenectDevice::getVideoBufferSize()      in ccnagzxR.o
      Freenect::FreenectDevice::FreenectDevice(_freenect_context_, int)in ccnagzxR.o
      DepthJSDevice::DepthJSDevice(_freenect_context_, int)in ccnagzxR.o
      initFreenect()     in ccQLBedv.o
      rgb_cb(_freenect_device_, void_, unsigned int)in ccQLBedv.o
  "_freenect_get_current_depth_mode", referenced from:
      Freenect::FreenectDevice::getDepthBufferSize()      in ccnagzxR.o
  "_freenect_set_video_mode", referenced from:
      Freenect::FreenectDevice::FreenectDevice(_freenect_context_, int)in ccnagzxR.o
      initFreenect()     in ccQLBedv.o
  "_freenect_find_depth_mode", referenced from:
      Freenect::FreenectDevice::FreenectDevice(_freenect_context_, int)in ccnagzxR.o
      DepthJSDevice::DepthJSDevice(_freenect_context_, int)in ccnagzxR.o
      initFreenect()     in ccQLBedv.o
      depth_cb(_freenect_device_, void_, unsigned int)in ccQLBedv.o
  "_freenect_set_depth_mode", referenced from:
      Freenect::FreenectDevice::FreenectDevice(_freenect_context_, int)in ccnagzxR.o
      initFreenect()     in ccQLBedv.o
ld: symbol(s) not found for architecture i386
collect2: ld returned 1 exit status

Little help?

**Comment by royshil** [comment]
@rubikzube The new version of the Chrome plugin is in firebreath-plugin (the npapi-plugin is now retired). You should be able to complie & install using the instruction in the readme.
