### ISSUE TITLE
InitDepthJS function is missing in Safari Extension

### ISSUE THREAD

**Issue by marr** [doug/depthjs#23]
Hi,
Signed the app and installed the safari extension. When I click "Inspect Global Page" in the Extensions Builder I am getting a TypeError on line 142 of backend.js:

var success = DepthJS.pluginObj.InitDepthJS(); 

Im not sure if there is an issue, but this line is coming from the // NPAPI PLUGIN BASED BACKEND -------- section of backend.js. Is this expected?

**Comment by jcraane** [comment]
Hi,

I do get the same issue as you, the specific error I get is: TypeError: 'undefined' is not a function (evaluating 'DepthJS.pluginObj.InitDepthJS()') coming from backend.js.

Did you resolve this issue yet?

**Comment by marr** [comment]
Jamie i cant remember now if i was able to get pAst this. Did you set up the safari project certificate correctly?

**Comment by jcraane** [comment]
Yes, I do have a Safari develop certificate setup and I am able to install the plugin. The extension is loaded by Safari. The error is thrown when I access the background.html page from the extension.

**Comment by royshil** [comment]
@jcraane There is a new Safari version up, with the function implemented, should work now.

**Comment by nm90** [comment]
@royshil
I am having an issue with the same method, but in the chrome-extension for Windows.  My background.html shows the error as an Uncaught TypeError: Object#<HTMLEmbededElement> has no method 'InitDepthJS'

My experience with JS is pretty limited, so I'm having trouble tracing around trying to find out what is actually going on here.

Any help much appreciated! Thanks!

**Comment by jblanche** [comment]
Same here on Safari (Version 5.1.7 (7534.57.2)). 

![Safari Screenshot](http://i.imgur.com/5tK6d.png)

Any help much appreciated too :)

**Comment by tan-c** [comment]
@nm90 hey man i am having the same issue with chrome. have you managed to find a solution yet? i realize that there is a warning generated at the extension page as manifest version 1 is getting out of date. i dun know if this is the root cause
