### ISSUE TITLE
Demo html/js not working

### ISSUE THREAD

**Issue by markstroeve** [doug/depthjs#24]
I've got the Chrome plugin working on my mac,I can use gestures. 
Next i wanted to check out the basic JS demo which is included in the repository.

But this demo doesn't seem te be working. I keeps giving the default text (Kinect not connected).
And there seems to be no XHR or websocket traffic/connection .

Is the current demo broken?

**Comment by royshil** [comment]
Officially right now we only support the Safari plugin.

We are making efforts to port the Safari plugin to Chrome & Firefox (NPAPI).

Are you up for it?

Roy.

**Comment by markstroeve** [comment]
I used the Chrome version. Because i couldn't get the Safari plugin/extension working.
I followed the instructions but when i want to build i get a lot of errors most of them are about missing includes/requires.
Do i need to add paths to NITE/OpenNi somewhere?

**Comment by royshil** [comment]
Indeed you do.
What are the errors that you get?

Roy.

**Comment by markstroeve** [comment]
These are the errors.
There are also a bunch of warnings, btw i've used Xcode4.

/Users/mark/Development/doug-depthjs-f404b8d/webkit-plugin-mac/openni_backend.cpp
XnOpenNI.h: No such file or directory
XnCppWrapper.h: No such file or directory
XnHash.h: No such file or directory
XnLog.h: No such file or directory
XnUSB.h: No such file or directory
XnVNite.h: No such file or directory
Expected `;' at end of input
Expected`}' at end of input
file://localhost/Users/mark/Development/doug-depthjs-f404b8d/webkit-plugin-mac/openni_backend.cpp:
error: Lexical or Preprocessor Issue: 'XnOpenNI.h' file not found

/Users/mark/Development/doug-depthjs-f404b8d/webkit-plugin-mac/HandMessageListener.h
XnVPointControl.h: No such file or directory
XnVFlowRouter.h: No such file or directory
XnVSwipeDetector.h: No such file or directory
XnVSelectableSlider1D.h: No such file or directory
XnVSteadyDetector.h: No such file or directory
XnVBroadcaster.h: No such file or directory
XnVPushDetector.h: No such file or directory
XnVWaveDetector.h: No such file or directory
XnVSessionManager.h: No such file or directory
XnVCircleDetector.h: No such file or directory
Expected class-name before '{' token
'xn' has not been declared
Expected `)' before 'depthGenerator'
'XnVMessage' has not been declared
Variable or field 'XN_CALLBACK_TYPE' declared void
Expected ';' before 'Swipe_Left'
Expected`;' before 'static'
Variable or field 'XN_CALLBACK_TYPE' declared void
Expected ';' before 'Swipe_Right'
Expected `;' before 'static'
Variable or field 'XN_CALLBACK_TYPE' declared void
Expected ';' before 'Swipe_Up'
Expected`;' before 'static'
Variable or field 'XN_CALLBACK_TYPE' declared void
Expected ';' before 'Swipe_Down'
Expected `;' before 'static'
Variable or field 'XN_CALLBACK_TYPE' declared void
Expected ';' before 'Push_Pushed'
Expected`;' before 'static'
Variable or field 'XN_CALLBACK_TYPE' declared void
Expected ';' before 'ACircle'
'XnVPointControl' has not been declared
'm_pPushDetector' was not declared in this scope
'm_pCircleDetector' was not declared in this scope
'm_pSwipeDetector' was not declared in this scope
Expected unqualified-id at end of input
XnCppWrapper.h: No such file or directory
XnVPointControl.h: No such file or directory
XnVFlowRouter.h: No such file or directory
XnVSwipeDetector.h: No such file or directory
XnVSelectableSlider1D.h: No such file or directory
XnVSteadyDetector.h: No such file or directory
XnVBroadcaster.h: No such file or directory
XnVPushDetector.h: No such file or directory
XnVWaveDetector.h: No such file or directory
XnVSessionManager.h: No such file or directory
XnVCircleDetector.h: No such file or directory
Expected class-name before '{' token
'xn' has not been declared
Expected `)' before 'depthGenerator'
'XnVMessage' has not been declared
Variable or field 'XN_CALLBACK_TYPE' declared void
Expected ';' before 'Swipe_Left'
Expected`;' before 'static'
Variable or field 'XN_CALLBACK_TYPE' declared void
Expected ';' before 'Swipe_Right'
Expected `;' before 'static'
Variable or field 'XN_CALLBACK_TYPE' declared void
Expected ';' before 'Swipe_Up'
Expected`;' before 'static'
Variable or field 'XN_CALLBACK_TYPE' declared void
Expected ';' before 'Swipe_Down'
Expected `;' before 'static'
Variable or field 'XN_CALLBACK_TYPE' declared void
Expected ';' before 'Push_Pushed'
Expected`;' before 'static'
Variable or field 'XN_CALLBACK_TYPE' declared void
Expected ';' before 'ACircle'
Expected `;' at end of input
Expected`}' at end of input
'XnVPointControl' has not been declared
'm_pPushDetector' was not declared in this scope
'm_pCircleDetector' was not declared in this scope
'm_pSwipeDetector' was not declared in this scope
Expected unqualified-id at end of input

2011/10/7 royshil
reply@reply.github.com:

> Indeed you do.
> What are the errors that you get?
> 
> Roy.
> 
> On Fri, Oct 7, 2011 at 9:56 AM, markstroeve <

**Comment by royshil** [comment]
This is obviously a problem where the compiler can't find the OpenNI
includes.

Please download the binaries of Openni and Nite from the urls in the readme.
Run their installation scripts.
Then set Xcode to find the includes (the install puts them usually in
/usr/..).

R.
 On Oct 7, 2011 10:09 AM, "markstroeve" <
reply@reply.github.com>
wrote:

> These are the errors.
> There are also a bunch of warnings, btw i've used Xcode4.
> 
> /Users/mark/Development/doug-depthjs-f404b8d/webkit-plugin-mac/openni_backend.cpp
> XnOpenNI.h: No such file or directory
> XnCppWrapper.h: No such file or directory
> XnHash.h: No such file or directory
> XnLog.h: No such file or directory
> XnUSB.h: No such file or directory
> XnVNite.h: No such file or directory
> Expected `;' at end of input
> Expected`}' at end of input
> 
> file://localhost/Users/mark/Development/doug-depthjs-f404b8d/webkit-plugin-mac/openni_backend.cpp:
> error: Lexical or Preprocessor Issue: 'XnOpenNI.h' file not found
> 
> /Users/mark/Development/doug-depthjs-f404b8d/webkit-plugin-mac/HandMessageListener.h
> XnVPointControl.h: No such file or directory
> XnVFlowRouter.h: No such file or directory
> XnVSwipeDetector.h: No such file or directory
> XnVSelectableSlider1D.h: No such file or directory
> XnVSteadyDetector.h: No such file or directory
> XnVBroadcaster.h: No such file or directory
> XnVPushDetector.h: No such file or directory
> XnVWaveDetector.h: No such file or directory
> XnVSessionManager.h: No such file or directory
> XnVCircleDetector.h: No such file or directory
> Expected class-name before '{' token
> 'xn' has not been declared
> Expected `)' before 'depthGenerator'
> 'XnVMessage' has not been declared
> Variable or field 'XN_CALLBACK_TYPE' declared void
> Expected ';' before 'Swipe_Left'
> Expected`;' before 'static'
> Variable or field 'XN_CALLBACK_TYPE' declared void
> Expected ';' before 'Swipe_Right'
> Expected `;' before 'static'
> Variable or field 'XN_CALLBACK_TYPE' declared void
> Expected ';' before 'Swipe_Up'
> Expected`;' before 'static'
> Variable or field 'XN_CALLBACK_TYPE' declared void
> Expected ';' before 'Swipe_Down'
> Expected `;' before 'static'
> Variable or field 'XN_CALLBACK_TYPE' declared void
> Expected ';' before 'Push_Pushed'
> Expected`;' before 'static'
> Variable or field 'XN_CALLBACK_TYPE' declared void
> Expected ';' before 'ACircle'
> 'XnVPointControl' has not been declared
> 'm_pPushDetector' was not declared in this scope
> 'm_pCircleDetector' was not declared in this scope
> 'm_pSwipeDetector' was not declared in this scope
> Expected unqualified-id at end of input
> XnCppWrapper.h: No such file or directory
> XnVPointControl.h: No such file or directory
> XnVFlowRouter.h: No such file or directory
> XnVSwipeDetector.h: No such file or directory
> XnVSelectableSlider1D.h: No such file or directory
> XnVSteadyDetector.h: No such file or directory
> XnVBroadcaster.h: No such file or directory
> XnVPushDetector.h: No such file or directory
> XnVWaveDetector.h: No such file or directory
> XnVSessionManager.h: No such file or directory
> XnVCircleDetector.h: No such file or directory
> Expected class-name before '{' token
> 'xn' has not been declared
> Expected `)' before 'depthGenerator'
> 'XnVMessage' has not been declared
> Variable or field 'XN_CALLBACK_TYPE' declared void
> Expected ';' before 'Swipe_Left'
> Expected`;' before 'static'
> Variable or field 'XN_CALLBACK_TYPE' declared void
> Expected ';' before 'Swipe_Right'
> Expected `;' before 'static'
> Variable or field 'XN_CALLBACK_TYPE' declared void
> Expected ';' before 'Swipe_Up'
> Expected`;' before 'static'
> Variable or field 'XN_CALLBACK_TYPE' declared void
> Expected ';' before 'Swipe_Down'
> Expected `;' before 'static'
> Variable or field 'XN_CALLBACK_TYPE' declared void
> Expected ';' before 'Push_Pushed'
> Expected`;' before 'static'
> Variable or field 'XN_CALLBACK_TYPE' declared void
> Expected ';' before 'ACircle'
> Expected `;' at end of input
> Expected`}' at end of input
> 'XnVPointControl' has not been declared
> 'm_pPushDetector' was not declared in this scope
> 'm_pCircleDetector' was not declared in this scope
> 'm_pSwipeDetector' was not declared in this scope
> Expected unqualified-id at end of input
> 
> 2011/10/7 royshil
> reply@reply.github.com:
> 
> > Indeed you do.
> > What are the errors that you get?
> > 
> > Roy.
> > 
> > On Fri, Oct 7, 2011 at 9:56 AM, markstroeve <

**Comment by mairead** [comment]
I've installed the chrome extension and am getting the same error:

DepthJS Console

No Kinect / DepthJS detected

Is the chrome extension not supported? 

I did receive several warnings when I compiled :

depthjs.cc:162: warning: ‘bool setupDevice()’ defined but not used
ocv_freenect.cpp: In function ‘void\* ocvFreenectThread(void*)’:
ocv_freenect.cpp:377: warning: comparison between signed and unsigned integer expressions
ocv_freenect.cpp:383: warning: comparison between signed and unsigned integer expressions
ocv_freenect.cpp:447: warning: comparison between signed and unsigned integer expressions
bg_fg_blobs.cpp: In function ‘cv::Scalar refineSegments(const cv::Mat&, cv::Mat&, cv::Mat&, std::vectorcv::Point_<int, std::allocatorcv::Point_<int > >&, std::vectorcv::Point_<int, std::allocatorcv::Point_<int > >&, cv::Point2i&)’:
bg_fg_blobs.cpp:51: warning: comparison between signed and unsigned integer expressions
bg_fg_blobs.cpp:59: warning: comparison between signed and unsigned integer expressions
bg_fg_blobs.cpp:66: warning: comparison between signed and unsigned integer expressions

Are these the problem? or is the chrome extension not supported as mentioned above?

**Comment by royshil** [comment]
@mairead
Please remove ocv_freenect.cpp and bg_fg_blobs.cpp from the build. They are
deprecated...
The errors should not bug you now :)

As for the missing Kinect, well.. make sure everything is connected.
I usually test everything by running an OpenNI already-compiled example...

Roy.

On Sun, Jan 8, 2012 at 1:40 PM, mairead <
reply@reply.github.com

**Comment by mairead** [comment]
@royshil 

Thanks, will remove the deprecated libs. For clarification when I am trying to run the demo app I have already connected the kinnect and successfully run both the glview app and the chrome extension that displays the first and second blob views. These are all working. It is only the demo page in the developers API I can't see. I was going to try building the safari extension, to see if I had more luck with that instead unless you have a different suggestion? 

I'm not sure what you mean when you say an already-compiled example of OpenNi

**Comment by royshil** [comment]
@mairead
The demo app will actually not show anything on screen.. it's just an
example of the API.
You should be able to see stuff in the Javascript console though.

The OpenNI examples are indeed "glview" and the likes of that.

Roy.

On Mon, Jan 9, 2012 at 11:37 AM, mairead <
reply@reply.github.com
