### ISSUE TITLE
chrome and safari installation

### ISSUE THREAD

**Issue by husk00** [doug/depthjs#25]
Hi people,
I'm trying to get this working on a snowLeopard machine, with safari and chrome. The chrome version seems to be installed properly but after 3 second the blob windows is get freeze. I'm trying now the safari version, I have installed the extension but I can't find how to launch it and still don't get what to do with webkit webplugin.
I know that you are working on many things but a little help on figurate how this work would be very appreciate.
cheers
husk

**Comment by plutobium** [comment]
Hi!

Maybe this helps:

https://github.com/doug/depthjs/issues/26

Cheers!
