### ISSUE TITLE
Building Code

### ISSUE THREAD

**Issue by willcampos** [doug/depthjs#3]
Hi, I am trying to build the code to test the example, After 3 days of work, I have almost everything working.

I think libfreenect has change a bit, not I am using the last version and the source code that you have for ocv_freenect.cpp is not building anymore.

ocv_freenect.cpp: In function ‘void depth_cb(freenect_device_, void_, uint32_t)’:
ocv_freenect.cpp:56: error: ‘FREENECT_DEPTH_SIZE’ was not declared in this scope
ocv_freenect.cpp: At global scope:
ocv_freenect.cpp:63: error: ‘freenect_pixel’ has not been declared
ocv_freenect.cpp: In function ‘void rgb_cb(freenect_device_, int_, uint32_t)’:
ocv_freenect.cpp:68: error: ‘FREENECT_RGB_SIZE’ was not declared in this scope
ocv_freenect.cpp: In function ‘int initFreenect()’:
ocv_freenect.cpp:125: error: ‘freenect_set_rgb_callback’ was not declared in this scope
ocv_freenect.cpp:126: error: ‘FREENECT_FORMAT_RGB’ was not declared in this scope
ocv_freenect.cpp:126: error: ‘freenect_set_rgb_format’ was not declared in this scope
ocv_freenect.cpp:127: error: ‘FREENECT_FORMAT_11_BIT’ was not declared in this scope
ocv_freenect.cpp:130: error: ‘freenect_start_rgb’ was not declared in this scope
ocv_freenect.cpp: In function ‘int main(int, char*_)’:
ocv_freenect.cpp:321: error: ‘freenect_set_rgb_callback’ was not declared in this scope
ocv_freenect.cpp:322: error: ‘FREENECT_FORMAT_RGB’ was not declared in this scope
ocv_freenect.cpp:322: error: ‘freenect_set_rgb_format’ was not declared in this scope
ocv_freenect.cpp:323: error: ‘FREENECT_FORMAT_11_BIT’ was not declared in this scope
ocv_freenect.cpp:326: error: ‘freenect_start_rgb’ was not declared in this scope
ocv_freenect.cpp:401: warning: comparison between signed and unsigned integer expressions
ocv_freenect.cpp:407: warning: comparison between signed and unsigned integer expressions
ocv_freenect.cpp:466: warning: comparison between signed and unsigned integer expressions
make: *_\* [ocv_freenect.o] Error 1

Can anyone help me out? or at least point me to the right libfreenect distribution/version.

Thanks,

Wilmar

**Comment by doug** [comment]
just pushed an updated version, with modified code for the latest libfreenect

**Comment by willcampos** [comment]
It work perfect.
Question, in the makefile i have to change -Wall $(shell pkg-config --cflags opencv libzmq
 libusb)
for
-Wall $(shell pkg-config --cflags opencv libzmq
 libusb-1.0)

do you know why i have to include -1.0 in libusb in order to recognize the library?

**Comment by azinman** [comment]
I would guess that's a libfreenet-specific dependency?
