### ISSUE TITLE
plugin errors after openni backend thread

### ISSUE THREAD

**Issue by pxue** [doug/depthjs#30]
I built the plugin without a problem, loaded it up manually in chrome and tried to inspect the popup. This is what i'm getting: 
![error](http://i.imgur.com/DGl5w.png), and the popup just shows up as crashed plugin. Any clue? Thanks!

**Comment by royshil** [comment]
@pxue I'm working on the Windows resources recovery right now
Basically the problem is the location of the Sample-Tracking.xml file.
It should be alongside the plugin, but it's still not finding it. Shortly it will be fixed.

**Comment by royshil** [comment]
now sorted out
please rebuild and add to chrome again
