### ISSUE TITLE
Build Issue. error LNK2001

### ISSUE THREAD

**Issue by JohnRSim** [doug/depthjs#32]
Hey Guys; having a few issues with the firebreath plugin build - 

I build the script -
C:\Users\John\Downloads\firebreath-FireBreath-firebreath-1.6.0rc2-93-g0da59d6\firebreath-FireBreath-0da59d6\prep2010.cmd . "-DOpenNI_LIBRARY=C:\Program Files\OpenNI\Lib64" "-DNITE_LIBRARY=C:\Program Files\PrimeSense\NITE\Lib64" "-DNITE_INCLUDE_DIR=C:\Program Files\PrimeSense\NITE\Include"

Log-
Using projects in: "C:\Users\John\Downloads\doug-depthjs-a5c3db2\doug-depthjs-a5c3db2\firebreath-plugin"
Generating build files in: "C:\Users\John\Downloads\doug-depthjs-a5c3db2\doug-depthjs-a5c3db2\firebreath-plugin\build"
NOTE: The build files in "C:\Users\John\Downloads\doug-depthjs-a5c3db2\doug-depthjs-a5c3db2\firebreath-plugin\build" should _NEVER_ be modified directly.
When needed, make project changes in cmake files and re-run this script.
  Project-specific cmake files are found in [plugin dir]\CMakeLists.txt and
  [plugin dir]\Win\projectDef.cmake.
Note that parameters for cmake should be enclosed in double quotes, e.g. "-DVERBOSE=1"
CMAKE parameters: "-DOpenNI_LIBRARY=C:\Program Files\OpenNI\Lib64" "-DNITE_LIBRARY=C:\Program Files\PrimeSense\NITE\Lib64" "-DNITE_INCLUDE_DIR=C:\Program Files\PrimeSense\NITE\Include"

C:\Users\John\Downloads\doug-depthjs-a5c3db2\doug-depthjs-a5c3db2\firebreath-plugin\build>cmake -G "Visual Studio 10" -DFB_PROJECTS_DIR="C:\Users\John\Downloads\doug-depthjs-a5c3db2\doug-depthjs-a5c3db2\firebreath-plugin" "-DOpenNI_LIBRARY=C:\Program Files\OpenNI\Lib64" "-DNITE_LIBRARY=C:\Program Files\PrimeSense\NITE\Lib64" "-DNITE_INCLUDE_DIR=C:\Program Files\PrimeSense\NITE\Include" "C:\Users\John\Downloads\firebreath-FireBreath-firebreath-1.6.0rc2-93-g0da59d6\firebreath-FireBreath-0da59d6"
-- Check for working C compiler using: Visual Studio 10
-- Check for working C compiler using: Visual Studio 10 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 10
-- Check for working CXX compiler using: Visual Studio 10 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Visual Studio dir: c:/Program Files (x86)/Microsoft Visual Studio 10.0
-- Found ATL include dir: C:/WinDDK/7600.16385.1/inc/atl71
-- Found ATL lib dir: C:/WinDDK/7600.16385.1/lib/ATL/i386
-- Found MFC include dir: C:/WinDDK/7600.16385.1/inc/mfc42
-- Balanced size/speed optimization
project dir: C:/Users/John/Downloads/doug-depthjs-a5c3db2/doug-depthjs-a5c3db2/firebreath-plugin
Single project: C:/Users/John/Downloads/doug-depthjs-a5c3db2/doug-depthjs-a5c3db2/firebreath-plugin
Generating plugin configuration files in C:/Users/John/Downloads/doug-depthjs-a5c3db2/doug-depthjs-a5c3db2/firebreath-plugin/build/projects/depthjsplugin/gen
-- Try to look here: C:/Program Files/OpenNI/Include/;D:/Program Files/OpenNI/Include/
-- Found OpenNI: C:/Program Files/OpenNI/Lib64
-- OpenNI found in C:/Program Files/OpenNI/Include
-- Try to look here: C:/Program Files/NITE/Include/;D:/Program Files/NITE/Include/
-- Found NITE: C:/Program Files/PrimeSense/NITE/Lib64
-- NITE found in C:/Program Files/PrimeSense/NITE/Include
-- setting output directory for simple_templater to C:/Users/John/Downloads/doug-depthjs-a5c3db2/doug-depthjs-a5c3db2/firebreath-plugin
Configuring C:/Users/John/Downloads/doug-depthjs-a5c3db2/doug-depthjs-a5c3db2/firebreath-plugin/Win/WiX/depthjspluginInstaller.wxs -> C:/Users/John/Downloads/doug-depthjs-a5c3db2/doug-depthjs-a5c3db2/firebreath-plugin/build/projects/depthjsplugin/depthjspluginInstaller.wxs
-- Configuring done
WARNING: Target "depthjsplugin" requests linking to directory "C:/Program Files/OpenNI/Lib64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "depthjsplugin" requests linking to directory "C:/Program Files/PrimeSense/NITE/Lib64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "depthjsplugin" requests linking to directory "C:/Program Files/OpenNI/Lib64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "depthjsplugin" requests linking to directory "C:/Program Files/PrimeSense/NITE/Lib64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "depthjsplugin" requests linking to directory "C:/Program Files/OpenNI/Lib64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "depthjsplugin" requests linking to directory "C:/Program Files/PrimeSense/NITE/Lib64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "depthjsplugin" requests linking to directory "C:/Program Files/OpenNI/Lib64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "depthjsplugin" requests linking to directory "C:/Program Files/PrimeSense/NITE/Lib64".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: C:/Users/John/Downloads/doug-depthjs-a5c3db2/doug-depthjs-a5c3db2/firebreath-plugin/build

Then when I build it I get the following issue - 

10>     Creating library C:/Users/John/Downloads/doug-depthjs-a5c3db2/doug-depthjs-a5c3db2/firebreath-plugin/build/projects/depthjsplugin/Debug/npdepthjsplugin.lib and object C:/Users/John/Downloads/doug-depthjs-a5c3db2/doug-depthjs-a5c3db2/firebreath-plugin/build/projects/depthjsplugin/Debug/npdepthjsplugin.exp
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnContextRelease
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: unsigned int __thiscall XnVCircleDetector::SetMinRadius(float)" (__imp_?SetMinRadius@XnVCircleDetector@@QAEIM@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void \* __thiscall XnVCircleDetector::RegisterCircle(void _,void (__stdcall_)(float,int,struct XnVCircle const _,void *))" (__imp_?RegisterCircle@XnVCircleDetector@@QAEPAXPAXP6GXMHPBUXnVCircle@@0@Z@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVCircleDetector::OnPrimaryPointDestroy(unsigned int)" (__imp_?OnPrimaryPointDestroy@XnVCircleDetector@@UAEXI@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVCircleDetector::OnPrimaryPointUpdate(struct XnVHandPointContext const *)" (__imp_?OnPrimaryPointUpdate@XnVCircleDetector@@UAEXPBUXnVHandPointContext@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVCircleDetector::OnPrimaryPointCreate(struct XnVHandPointContext const *,struct XnVector3D const &)" (__imp_?OnPrimaryPointCreate@XnVCircleDetector@@UAEXPBUXnVHandPointContext@@ABUXnVector3D@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall XnVCircleDetector::~XnVCircleDetector(void)" (__imp_??1XnVCircleDetector@@UAE@XZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall XnVCircleDetector::XnVCircleDetector(char const *)" (__imp_??0XnVCircleDetector@@QAE@PBD@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: unsigned int __thiscall XnVMessageGenerator::AddListener(class XnVMessageListener *)" (__imp_?AddListener@XnVMessageGenerator@@QAEIPAVXnVMessageListener@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnOSMalloc
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnForceShutdown
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) protected: virtual void __thiscall XnVSessionManager::SessionStop(void)" (__imp_?SessionStop@XnVSessionManager@@MAEXXZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVSessionManager::ClearQueue(void)" (__imp_?ClearQueue@XnVSessionManager@@UAEXXZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual unsigned int __thiscall XnVSessionManager::TrackPoint(struct XnVector3D const &)" (__imp_?TrackPoint@XnVSessionManager@@UAEIABUXnVector3D@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual unsigned int __thiscall XnVSessionManager::ForceSession(struct XnVector3D const &)" (__imp_?ForceSession@XnVSessionManager@@UAEIABUXnVector3D@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual unsigned int __thiscall XnVSessionManager::EndSession(void)" (__imp_?EndSession@XnVSessionManager@@UAEIXZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual unsigned int __thiscall XnVSessionManager::LosePoints(void)" (__imp_?LosePoints@XnVSessionManager@@UAEIXZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual unsigned int __thiscall XnVSessionManager::LosePoint(unsigned int)" (__imp_?LosePoint@XnVSessionManager@@UAEII@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVSessionManager::Update(class XnVMessage *)" (__imp_?Update@XnVSessionManager@@UAEXPAVXnVMessage@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVSessionManager::Update(class xn::Context const *)" (__imp_?Update@XnVSessionManager@@UAEXPBVContext@xn@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: unsigned int __thiscall XnVSessionManager::Initialize(class xn::Context *,char const *,char const *,class xn::HandsGenerator *,class xn::GestureGenerator *,class xn::GestureGenerator *)" (__imp_?Initialize@XnVSessionManager@@QAEIPAVContext@xn@@PBD1PAVHandsGenerator@3@PAVGestureGenerator@3@3@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall XnVSessionManager::~XnVSessionManager(void)" (__imp_??1XnVSessionManager@@UAE@XZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall XnVSessionManager::XnVSessionManager(char const *)" (__imp_??0XnVSessionManager@@QAE@PBD@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnEnumerationErrorsAllocate
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnOSFree
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void \* __thiscall XnVPointControl::RegisterNoPoints(void *,void (__stdcall_)(void _))" (__imp_?RegisterNoPoints@XnVPointControl@@QAEPAXPAXP6GX0@Z@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVPointControl::Update(class XnVMessage *)" (__imp_?Update@XnVPointControl@@UAEXPAVXnVMessage@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVPointControl::Update(class XnVMultipleHands const &)" (__imp_?Update@XnVPointControl@@UAEXABVXnVMultipleHands@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall XnVPointControl::~XnVPointControl(void)" (__imp_??1XnVPointControl@@UAE@XZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall XnVPointControl::XnVPointControl(char const *)" (__imp_??0XnVPointControl@@QAE@PBD@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnRegisterToGestureIntermediateStageCompleted
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnUSBInit
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnProductionNodeRelease
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnInitFromXmlFileEx
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnConvertRealWorldToProjective
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnFindExistingRefNodeByType
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnEnumerationErrorsToString
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) protected: virtual void __thiscall XnVFlowRouter::OpenNewSession(void)" (__imp_?OpenNewSession@XnVFlowRouter@@MAEXXZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) protected: virtual void __thiscall XnVFlowRouter::CloseOldSession(void)" (__imp_?CloseOldSession@XnVFlowRouter@@MAEXXZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVFlowRouter::ClearQueue(void)" (__imp_?ClearQueue@XnVFlowRouter@@UAEXXZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVFlowRouter::Update(class XnVMessage *)" (__imp_?Update@XnVFlowRouter@@UAEXPAVXnVMessage@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: unsigned int __thiscall XnVFlowRouter::SetActive(class XnVMessageListener *)" (__imp_?SetActive@XnVFlowRouter@@QAEIPAVXnVMessageListener@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall XnVFlowRouter::~XnVFlowRouter(void)" (__imp_??1XnVFlowRouter@@UAE@XZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall XnVFlowRouter::XnVFlowRouter(char const *)" (__imp_??0XnVFlowRouter@@QAE@PBD@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnContextAddRef
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __thiscall XnVSwipeDetector::SetMotionSpeedThreshold(float)" (__imp_?SetMotionSpeedThreshold@XnVSwipeDetector@@QAEXM@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void \* __thiscall XnVSwipeDetector::RegisterSwipeRight(void *,void (__stdcall_)(float,float,void _))" (__imp_?RegisterSwipeRight@XnVSwipeDetector@@QAEPAXPAXP6GXMM0@Z@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void \* __thiscall XnVSwipeDetector::RegisterSwipeLeft(void *,void (__stdcall_)(float,float,void _))" (__imp_?RegisterSwipeLeft@XnVSwipeDetector@@QAEPAXPAXP6GXMM0@Z@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void \* __thiscall XnVSwipeDetector::RegisterSwipeDown(void *,void (__stdcall_)(float,float,void _))" (__imp_?RegisterSwipeDown@XnVSwipeDetector@@QAEPAXPAXP6GXMM0@Z@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void \* __thiscall XnVSwipeDetector::RegisterSwipeUp(void *,void (__stdcall_)(float,float,void _))" (__imp_?RegisterSwipeUp@XnVSwipeDetector@@QAEPAXPAXP6GXMM0@Z@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVSwipeDetector::OnPrimaryPointDestroy(unsigned int)" (__imp_?OnPrimaryPointDestroy@XnVSwipeDetector@@UAEXI@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVSwipeDetector::OnPrimaryPointReplace(unsigned int,struct XnVHandPointContext const *)" (__imp_?OnPrimaryPointReplace@XnVSwipeDetector@@UAEXIPBUXnVHandPointContext@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVSwipeDetector::OnPrimaryPointUpdate(struct XnVHandPointContext const *)" (__imp_?OnPrimaryPointUpdate@XnVSwipeDetector@@UAEXPBUXnVHandPointContext@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVSwipeDetector::OnPrimaryPointCreate(struct XnVHandPointContext const *,struct XnVector3D const &)" (__imp_?OnPrimaryPointCreate@XnVSwipeDetector@@UAEXPBUXnVHandPointContext@@ABUXnVector3D@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall XnVSwipeDetector::~XnVSwipeDetector(void)" (__imp_??1XnVSwipeDetector@@UAE@XZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall XnVSwipeDetector::XnVSwipeDetector(int,char const *)" (__imp_??0XnVSwipeDetector@@QAE@HPBD@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnUSBCloseDevice
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnRegisterGestureCallbacks
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) protected: virtual void __thiscall XnVSessionGenerator::SessionMidGesture(char const *,struct XnVector3D const &,float)" (__imp_?SessionMidGesture@XnVSessionGenerator@@MAEXPBDABUXnVector3D@@M@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) protected: virtual void __thiscall XnVSessionGenerator::SessionStart(struct XnVector3D const &)" (__imp_?SessionStart@XnVSessionGenerator@@MAEXABUXnVector3D@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: unsigned int __thiscall XnVSessionGenerator::RegisterSession(void *,void (__stdcall_)(struct XnVector3D const &,void _),void (__stdcall_)(void _),void (__stdcall_)(char const _,struct XnVector3D const &,float,void *))" (__imp_?RegisterSession@XnVSessionGenerator@@QAEIPAXP6GXABUXnVector3D@@0@ZP6GX0@ZP6GXPBD1M0@Z@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnSetTrackingSmoothing
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnRegisterToGestureReadyForNextIntermediateStage
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnContextUnregisterFromShutdown
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnProductionNodeAddRef
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void \* __thiscall XnVPushDetector::RegisterPush(void *,void (__stdcall_)(float,float,void *))" (__imp_?RegisterPush@XnVPushDetector@@QAEPAXPAXP6GXMM0@Z@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVPushDetector::OnPrimaryPointUpdate(struct XnVHandPointContext const *)" (__imp_?OnPrimaryPointUpdate@XnVPushDetector@@UAEXPBUXnVHandPointContext@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVPushDetector::OnPrimaryPointCreate(struct XnVHandPointContext const *,struct XnVector3D const &)" (__imp_?OnPrimaryPointCreate@XnVPushDetector@@UAEXPBUXnVHandPointContext@@ABUXnVector3D@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall XnVPushDetector::~XnVPushDetector(void)" (__imp_??1XnVPushDetector@@UAE@XZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall XnVPushDetector::XnVPushDetector(char const *)" (__imp_??0XnVPushDetector@@QAE@PBD@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnEnumerationErrorsFree
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVMessageListener::ClearQueue(void)" (__imp_?ClearQueue@XnVMessageListener@@UAEXXZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVMessageListener::HandleCCMessages(class XnVMessage *)" (__imp_?HandleCCMessages@XnVMessageListener@@UAEXPAVXnVMessage@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnContextRegisterForShutdown
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnGetRefContextFromNodeHandle
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnGetStatusString
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnWaitOneUpdateAll
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnUSBSendControl
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnStartGeneratingAll
10>openni_backend.obj : error LNK2001: unresolved external symbol __imp__xnUSBOpenDevice
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVPointControl::OnNoPoints(void)" (__imp_?OnNoPoints@XnVPointControl@@UAEXXZ)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVPointControl::OnPrimaryPointDestroy(unsigned int)" (__imp_?OnPrimaryPointDestroy@XnVPointControl@@UAEXI@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVPointControl::OnPrimaryPointReplace(unsigned int,struct XnVHandPointContext const *)" (__imp_?OnPrimaryPointReplace@XnVPointControl@@UAEXIPBUXnVHandPointContext@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVPointControl::OnPrimaryPointUpdate(struct XnVHandPointContext const *)" (__imp_?OnPrimaryPointUpdate@XnVPointControl@@UAEXPBUXnVHandPointContext@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVPointControl::OnPrimaryPointCreate(struct XnVHandPointContext const *,struct XnVector3D const &)" (__imp_?OnPrimaryPointCreate@XnVPointControl@@UAEXPBUXnVHandPointContext@@ABUXnVector3D@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVPointControl::OnPointDestroy(unsigned int)" (__imp_?OnPointDestroy@XnVPointControl@@UAEXI@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVPointControl::OnPointUpdate(struct XnVHandPointContext const *)" (__imp_?OnPointUpdate@XnVPointControl@@UAEXPBUXnVHandPointContext@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVPointControl::OnPointCreate(struct XnVHandPointContext const *)" (__imp_?OnPointCreate@XnVPointControl@@UAEXPBUXnVHandPointContext@@@Z)
10>openni_backend.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall XnVMessageListener::Activate(int)" (__imp_?Activate@XnVMessageListener@@UAEXH@Z)
10>C:\Users\John\Downloads\doug-depthjs-a5c3db2\doug-depthjs-a5c3db2\firebreath-plugin\build\bin\depthjsplugin\Debug\npdepthjsplugin.dll : fatal error LNK1120: 89 unresolved externals

**Comment by JohnRSim** [comment]
My bad I hadn't pointed to the library.. 

Can you confirm that these are the right libraries?
\NITE\Lib\XnVNITE_1_5_2.lib
\OpenNI\Lib\openNI.lib

I have DepthJS + Kinect detected+!@
Hand not in view

I can't seem to get the hand activated -  if I run the sample niHandTracker.exe it recognises the wave.

**Comment by JohnRSim** [comment]
Restart and its working google etc..
Was expecting the blue ball on the demo page aswell but doesnt matter. 

Great work guys ;)

**Comment by royshil** [comment]
Sweet! You managed on your own... That is the best kind of issue

**Comment by webpapaya** [comment]
I'm getting the same error as described above.
Can you please tell me how you've solved it?

Thanks

**Comment by matthewkremer** [comment]
I have the same problem, what was your solution? I tried restarting, etc. and that did not solve the problem.

**Comment by webpapaya** [comment]
Hey Matthew,

I'm sorry but I currently haven't found any solution to get depthjs running. The main problem is, that some of the dependencies which are described in this article (http://info.abril.com.br/noticias/blogs/zonalivre/desenvolvimento/um-guia-para-hackear-o-kinect/) are deprecated and if you change to some newer versions the thing won't compile.

My solution was to install windows in a Virtual Machine and use kinectJS (http://kinect.childnodes.com/). The Problem is that it is sometimes really slow. In my point of few the best solution is to use another programming language like (c#, c++ or java).

Best regards,
Thomas

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.

---

Von: Matthew Kremer [notifications@github.com]
Gesendet: Donnerstag, 30. Mai 2013 18:24
An: doug/depthjs
Cc: Thomas Mayrhofer
Betreff: Re: [depthjs] Build Issue. error LNK2001 (#32)

I have the same problem, what was your solution? I tried restarting, etc. and that did not solve the problem.
