### ISSUE TITLE
raw depth map

### ISSUE THREAD

**Issue by chparsons** [doug/depthjs#36]
Hi, is there a way to get the full raw depth map (640x480) ?

and how can I get the rgb and filtered raw depth map from js?

thanks

**Comment by chmac** [comment]
This is exactly my question. Love node, love javascript, want to play with the kinect, but I want the raw depth map rather than a representation of a hand or whatever other magic is going on.

@chparsons Did you ever find an answer?

**Comment by chmac** [comment]
Just looked into this (a little) and I'm guessing this is not possible. From a quick scan of the stack, it seems like the depth map never reaches javascript. The kinect device generates a depth map. That's passed to OpenNI / Nite, where it's interpreted into bode tracking events, hand actions, and so on. Those events are in turn passed to javascript, browser plugin, and so on. Bottom line, depth map -> js, doesn't happen. I've only been looking for an hour or so, so I could well be wrong, but that's how it seems to me.

**Comment by chmac** [comment]
Oh, and it looks like there is an alternative in `npm install kinect`. https://github.com/pgte/node-kinect

**Comment by doug** [comment]
Yes, for node.js the npm lib you linked is probably much closer to what you need.
