### ISSUE TITLE
Chrome extension manifest version warning

### ISSUE THREAD

**Issue by mahsa-teimourikia** [doug/depthjs#39]
I have installed the chrome extension on Windows 7. However I cannot get it to work. After adding the extension to chrome it shows this warning (I am translating it from italian, therefore it might be a bit different than original english one): We are phasing out support for version 1 of the manifest file. Please upgrade to version 2.

The extension gets added and I can see the icon on the top right of my browser, but it does not do anything. Also when I click on the icon it gives me this error: Error 6 (net::ERR_FILE_NOT_FOUND): Impossible to find file or directory.

Any suggestions? Did I do something wrong for installing?

**Comment by lukefinsaas** [comment]
I get the same error, but haven't figured out how to fix it. Let me know if you do!

**Comment by ghost** [comment]
Hey....just noticed your comments and I've a question. Is it possible to get access on the RGBA camera of the kinect with javascript?`

I've already wrote one of the developer, there is no answer...

**Comment by lukefinsaas** [comment]
It seems like that's how they're doing it, they'd be the one's to say for sure.

**Comment by ghost** [comment]
Other idea could be to send an ajax request to our php-backend after identifying a gesture. in the php script, we could exec() a little c# program, which takes a picture and saves it on the server (we need this, because we want to manipulate the image with ImageMagick)

but it would be better, if there is a native solution in javascript.

**Comment by steven-king** [comment]
It seems this thread went a little off topic and dorment. This is still an outstanding issue. The Chrome plugin fails on install because of the if statement checking the manifest document. I am curious if updating the manifest.json and rebuilding the plugin will work. Has anyone successfully got this to work in the latest versions of Chrome?

**Comment by tan-c** [comment]
@mahsa-teimourikia i think manifest is not a problem as it at most generates a warning and its still used by the current version. popup.html is just for extra user interface and is not vital for the functions. if your program is not working you should check out the console on background.html for more information.

**Comment by steven-king** [comment]
Thanks @u0909067 @mahsa-teimourikia, you are correct and there are several other problems with the Chrome plugin. I do have a working version now and I will explain the changes in case others are having the same problem.  
1. the chrome.extensions.sendRequest method has been deprecated in newer versions of Chrome. It should be changed to .sendMessage in the chrome.js file.
2. Inline scripts are also deprecated in the background.html files so I created a new js file and moved the scripts there. 
3. I could be wrong but it seems in the latest version code the popup.html file is not there, which as you pointed out is not required. I copied from a previous release, moved the inline scripts and replaced sendRequest with sendMessage.
4. Updated the manifest.json to version 2 to avoid teh warning and replaced background_page with background.html and changed popup to default_popup.

This seems to be working on Chrome Mac Version 22.0.1229.94 and after further testing I will commit and submit a pull request.  

Thanks @u0909067 @mahsa-teimourikia, for replying and reminding me to share my changes.

**Comment by thevinci** [comment]
Nice @steven-king! For some reason, manifest version 2 is not pushed and I am still getting the background_page error when I load the chrome plugin.

![Screen Shot 2013-01-17 at 10 27 39 AM](https://f.cloud.github.com/assets/226341/75375/d6d64be6-60c2-11e2-8484-530cb02b9c67.png)

**Comment by steven-king** [comment]
I just downloaded from the master and installed the upacked extension into Chrome 24.0.1312.52 on Mac 10.8.2. 
The Manifest is built off of the json file which is there (https://github.com/doug/depthjs/blob/master/chrome-extension/manifest.json). 
If you are trying to install on windows you might have to update the https://github.com/doug/depthjs/blob/master/chrome-extension/manifest.json.WIN32
 with the same info found in the manifest.json. 
Thanks!

**Comment by thevinci** [comment]
Weird. Not sure how I somehow got the older version of the manifest. It works now. I'm on the Mac.

Did you have to build this as well? Did you get a build error?

![Screen Shot 2013-01-17 at 10 53 00 AM](https://f.cloud.github.com/assets/226341/75458/647c01ea-60c6-11e2-81b5-bf59f272f39a.png)

**Comment by royshil** [comment]
These two problems were addressed in the latest version (one was due to an update with FireBreath and the other to updates in Chrome's extension standards), please check out the code and try to compile.
