### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by DisizDream** [doug/depthjs#4]
Hi,

When I try to compile CV, I got this error : 

ocv_freenect.cpp: In function ‘void doHist(cv::Mat&, cv::Mat&)’:
ocv_freenect.cpp:231: error: no match for ‘operator-’ in ‘depthf - minVal’

I think it may come from my OpenCV version, which version are you using to compile? Thanks

**Comment by royshil** [comment]
We're using OpenCV 2.1.x
Indeed it is an API version problem, please update to the latest OpenCV.
