### ISSUE TITLE
Nothing Works

### ISSUE THREAD

**Issue by thevinci** [doug/depthjs#43]
Installed OpenNI, NITE, CMake, Firesheath and everything I can think of. Not sure what to do next. Probably going to give up and go to Windows now at this point and use the Microsoft SDK.
![Screen Shot 2013-01-17 at 4 51 11 PM](https://f.cloud.github.com/assets/226341/76621/7f52d1ce-60f8-11e2-9784-4435bbe1ffe0.png)

On Mountain Lion 10.8.

**Comment by royshil** [comment]
Actually it looks like it's working fine for you.
