### ISSUE TITLE
Chrome Extension: Object #<HTMLEmbedElement> has no method 'InitDepthJS'

### ISSUE THREAD

**Issue by ilessiivi** [doug/depthjs#47]
I have the Chrome extension installed on Chrome version 25.0.1364.36 (OS X 10.8.3). OpenNI, SensorKinect and NiTE are installed and NiTE demos are working. The Firebreath plugin was built without errors.

I've set up the simple DepthJS demo page and it says "Hand not in view" but none of the blobs open up. Error console for that page: 
- DepthJS: Loading Root
- DepthJS: Loading Depthose
- DepthJS: loading zflow
- DepthJS: Loading Panner
- DepthJS: Loading SelectorBox
- DepthJS: Loading event handlers
- DepthJS: Loading Event Link
- DepthJS Loading Chrome shit
- ["Initing DepthJS", Object]
- Initing selector box
- DepthJS: Event link init
- DepthJS: Registering eventPort on DepthJS supported web page
- Initting Depthose
- Finished initing, sticking in logo
- [img, selector: "img", context: document, init: function, selector: "", jquery: "1.4.4"…]
- ------Tue Apr 16 2013 19:02:42 GMT+0300 (EEST)
- ["   1 KinectInit; last = ", "DepthJS: event KinectInit"] 

Digging deeper, here's the error console for background.html:
- background.html Starting DepthJS
- Initing background.html message handling
- DepthJS Loading Chrome shit
- Starting DepthJS...
- Initing DepthJS background
- DepthJS: Initing Chrome background
- DepthJS: Initing port listener
- Connecting to Backend
- **Uncaught TypeError: Object #<HTMLEmbedElement> has no method 'InitDepthJS'**
- event port connected
- thumbnails port connected
- event port disconnected on tab 11
- thumbnails port disconnected on tab 11
- for all ports on this tab
- event port connected
- thumbnails port connected 

There was also an error about Content Security Policy directive: "script-src 'self' chrome-extension-resource:" but I got around that by removing jQuery script tag from background.html. JQuery is included on the DepthJS demo site that I'm trying to use so removing it from the extension didn't have any noticeable effect.

I'm not sure what the problem is here. There was an [issue](https://github.com/doug/depthjs/issues/23)  here in Github two years ago about the same problem on Safari, but it's closed as it was apparently fixed by a software update.

**Comment by royshil** [comment]
Looks like the same problem as https://github.com/doug/depthjs/issues/44
Please follow up there.
Basically, the plugin has not loaded.
If it did load you would have seen **depthjsplugin::onPluginReady** in the console, which is something the native plugin outputs when it loads.
