### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by Orion-M43** [doug/depthjs#5]
hi i'm having one problem, you could say to me where i can make the download of the lib "zmq.h" and "zmq.hpp",  Sorry for my English.

In file included from ocv_freenect.cpp:12:
zhelpers.hpp: In function ‘bool s_sendmore(zmq::socket_t&, const std::string&)’:
zhelpers.hpp:82: error: ‘ZMQ_SNDMORE’ was not declared in this scope
ocv_freenect.cpp: At global scope:
ocv_freenect.cpp:87: error: no matching function for call to ‘zmq::context_t::context_t(int)’
/usr/include/zmq.hpp:180: note: candidates are: zmq::context_t::context_t(const zmq::context_t&)
/usr/include/zmq.hpp:163: note:                 zmq::context_t::context_t(int, int, int)
ocv_freenect.cpp: In function ‘int main(int, char*_)’:
ocv_freenect.cpp:405: warning: comparison between signed and unsigned integer expressions
ocv_freenect.cpp:411: warning: comparison between signed and unsigned integer expressions
ocv_freenect.cpp:470: warning: comparison between signed and unsigned integer expressions
make: *_\* [ocv_freenect.o] Error 1

**Comment by royshil** [comment]
You can download ZeroMQ here: http://www.zeromq.org/intro:get-the-software

**Comment by Orion-M43** [comment]
thanks.
