### ISSUE TITLE
Errors while compiling cv module

### ISSUE THREAD

**Issue by nicois** [doug/depthjs#6]
On ubuntu 10.10, with the specified packages installed, I get errors when running 'make':

In file included from ocv_freenect.cpp:12:
zhelpers.hpp: In function ‘bool s_sendmore(zmq::socket_t&, const std::string&)’:
zhelpers.hpp:82: error: ‘ZMQ_SNDMORE’ was not declared in this scope
ocv_freenect.cpp: At global scope:
ocv_freenect.cpp:87: error: no matching function for call to ‘zmq::context_t::context_t(int)’

**Comment by nicois** [comment]
whoops just saw this was reported already

**Comment by royshil** [comment]
This looks like a libzmq version problem.
I am using 2.0.10 to compile. Try using that version
